# This is a config for E2B sandbox template.
# You can use template ID (u8w4jzut60mgigs4ofp9) or template name (askanyexpert-final) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("askanyexpert-final") # Sync sandbox
# sandbox = await AsyncSandbox.create("askanyexpert-final") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('askanyexpert-final')

team_id = "12c04104-e2c1-42a2-92a0-7625ffcba73a"
dockerfile = "e2b.Dockerfile"
template_name = "askanyexpert-final"
template_id = "u8w4jzut60mgigs4ofp9"
