# This is a config for E2B sandbox template.
# You can use template ID (hg663uyug6apnbavn230) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("hg663uyug6apnbavn230") # Sync sandbox
# sandbox = await AsyncSandbox.create("hg663uyug6apnbavn230") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('hg663uyug6apnbavn230')

team_id = "12c04104-e2c1-42a2-92a0-7625ffcba73a"
dockerfile = "e2b.Dockerfile"
template_id = "hg663uyug6apnbavn230"
